[package]
name = "axum_simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = '0.6.9'
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.9"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
